<x-adminLayout>
	<div class="px-4 md:px-8 py-4 md:py-0 md:pb-8">
		<div class="text-lg md:text-xl | font-semibold | text-title-color dark:text-dt-title-color | mb-4 px-2">
			Título (si se requiere)
		</div>

		<div class="border border-border-color dark:border-dt-border-color | rounded-lg | w-full | bg-white dark:bg-dt-dark | shadow-bottom dark:shadow-none | mb-6 p-4 leading-6">

			Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur, accusamus distinctio. Repudiandae obcaecati consectetur assumenda magni dolorum fugiat ab eveniet facilis nisi repellendus maiores iste atque fugit, quam laboriosam, laborum cupiditate minima ex rerum quas optio eaque. Illo nulla provident id saepe consectetur expedita eius eum quae facere hic quos ipsa debitis voluptatem odit accusamus explicabo suscipit ex, ducimus cupiditate? Officia eaque eum est facere corporis ratione pariatur illum. Quasi est labore minus officia sequi quod atque sunt nemo dolor illum, modi ipsa ad adipisci consectetur animi quam similique, ipsam tempore delectus ab deserunt obcaecati eos? Omnis ipsum, esse voluptas expedita ducimus quo iure quod nulla corporis pariatur dolorem facere recusandae? Rem nesciunt amet, sapiente alias, fugit voluptatem natus nulla in temporibus porro ratione provident, error neque eaque minima sit voluptatibus voluptas, impedit iure ut? Recusandae quaerat, accusamus. Molestiae sapiente quidem unde voluptatum assumenda inventore consequatur quasi doloribus temporibus dolore repudiandae praesentium omnis obcaecati consectetur necessitatibus, repellendus ipsa alias ut minima facere nulla! Optio distinctio placeat deleniti deserunt nobis itaque beatae repellat veritatis, voluptatibus numquam facilis praesentium quibusdam, quos eum doloremque perferendis. Odio, dolorem. Dicta totam iste saepe amet reprehenderit quod ad velit laudantium nisi porro repellendus maiores, repellat autem delectus, minima error, odio. Labore, perferendis, aspernatur! Debitis, repellat hic quaerat modi earum vero sequi, sunt, sed tempora, quis eum sint corporis eaque mollitia odio veritatis ullam eligendi. Eligendi, fugit quam ex nostrum, eum doloremque mollitia sint dolor incidunt? Autem excepturi, nam in ab, veniam delectus optio deserunt laborum similique labore possimus, nemo tempora qui expedita fugiat ipsam quia nesciunt soluta asperiores odio aperiam! Ut sit autem, cumque unde velit minus possimus enim maxime quos vel doloremque nobis officia sequi. Dicta debitis itaque qui corrupti aperiam neque, rerum, animi eaque atque perspiciatis quod magni ad placeat. Nemo, labore fuga quaerat!
		</div>

	</div>
</x-adminLayout>