<x-card class="sm:p-4 rounded-t-none">
    <div class="max-w-2xl mx-4 md:mx-auto my-4 rounded-lg bg-dt-darker border border-dt-border-color">
        <div class="border-b border-dt-border-color p-3 uppercase text-title-color dark:text-dt-title-color">
            Race
        </div>
        <div class="p-6">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas reiciendis inventore quos error quam minus id nisi commodi nesciunt a! Quibusdam architecto aperiam repudiandae hic consectetur pariatur ipsa dolorum enim beatae dignissimos, similique voluptatibus porro deleniti, ipsam voluptatem labore at neque sit obcaecati exercitationem vitae tenetur. Soluta quae porro quia deleniti esse reiciendis ducimus minus similique consectetur suscipit, dolorum dolores fugit ea laboriosam. Doloribus dolore non atque assumenda soluta possimus. Maxime, quia, illo. Iure voluptates quia eos cumque a amet doloremque laboriosam fuga aut porro mollitia impedit tempora quos reiciendis id facilis minima, vero. Commodi, quisquam qui incidunt rerum quae odio atque a eos delectus, ullam? Numquam quae assumenda, iure porro vel nobis, sint maxime dolor. Deserunt ullam porro iste, non commodi unde officiis minus nemo quaerat, perspiciatis recusandae quisquam explicabo eaque dolore, rerum animi veniam assumenda voluptates nesciunt aliquid quos. Vitae necessitatibus labore reiciendis assumenda, sit velit possimus officia ducimus exercitationem, aperiam aut laboriosam repellendus. Sed autem officia quis laudantium ducimus ratione saepe fuga dolorum consequuntur odio magni atque iste, voluptas dolores sit quam, tempore tenetur, blanditiis eius itaque ut. Sequi explicabo excepturi, assumenda impedit, distinctio cum, officia possimus aperiam libero temporibus inventore. Reprehenderit labore odit exercitationem excepturi quasi temporibus accusamus, maiores laudantium odio nam illo minima alias quisquam. Nisi deserunt ex est, voluptate similique autem placeat deleniti repudiandae impedit accusantium, maxime aspernatur in nesciunt culpa, molestiae, cum amet ipsa rerum? Illo perspiciatis, quidem odio, magnam voluptas eos voluptate necessitatibus, pariatur, dolor blanditiis veritatis rem quod! Inventore eligendi quisquam eos perspiciatis, laborum earum maiores vero animi vitae, voluptates, illo numquam dicta veniam! Rem incidunt consequatur commodi quasi repudiandae voluptatum, minus, magni vitae, maxime minima repellat esse itaque quis corporis, exercitationem iusto. Quibusdam corrupti deleniti, voluptate hic illum facere, ullam quia ab, recusandae optio vero officia, maiores eaque. Possimus, saepe.
        </div>

    </div>
</x-card>